"""add expires_at to user_tokens table

Revision ID: f0436b79c8b5
Revises: 1cb31978bb89
Create Date: 2026-07-10 11:11:25.628398

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0436b79c8b5'
down_revision: Union[str, None] = '1cb31978bb89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_column('user_tokens', 'expires_at')
    # ### end Alembic commands ###
