name: Docker Build

on:
  workflow_run:
    workflows: ["PR Checks"]
    types:
      - completed

jobs:
  build-dev:
    if: >
      github.event.workflow_run.conclusion == 'success'
      && (github.event.workflow_run.head_branch == 'develop')
    uses: ./.github/workflows/docker-build-reusable.yml
    permissions:
      contents: read
      packages: write
    with:
      dockerfile: docker/Dockerfile
      image_name: ghcr.io/cgiar-agwise/kvuno-api
      branch_ref: refs/heads/${{ github.event.workflow_run.head_branch }}
      branch_name: ${{ github.event.workflow_run.head_branch }}
      commit_sha: ${{ github.event.workflow_run.head_sha }}

  build-prod:
    if: >
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.head_branch == 'main'
    uses: ./.github/workflows/docker-build-reusable.yml
    permissions:
      contents: read
      packages: write
    with:
      dockerfile: docker/Dockerfile.prod.dockerfile
      image_name: ghcr.io/cgiar-agwise/kvuno-api
      branch_ref: refs/heads/${{ github.event.workflow_run.head_branch }}
      branch_name: ${{ github.event.workflow_run.head_branch }}
      commit_sha: ${{ github.event.workflow_run.head_sha }}

  build-worker:
    if: >
      github.event.workflow_run.conclusion == 'success'
      && (github.event.workflow_run.head_branch == 'main'
          || github.event.workflow_run.head_branch == 'develop'
          || startsWith(github.event.workflow_run.head_branch, 'beta/'))
    uses: ./.github/workflows/docker-build-reusable.yml
    permissions:
      contents: read
      packages: write
    with:
      dockerfile: docker/Dockerfile.worker
      image_name: ghcr.io/cgiar-agwise/kvuno-worker
      branch_ref: refs/heads/${{ github.event.workflow_run.head_branch }}
      branch_name: ${{ github.event.workflow_run.head_branch }}
      commit_sha: ${{ github.event.workflow_run.head_sha }}
